# -*- coding: utf-8 -*-
from . import test_log_call
from . import test_contact
from . import test_rapprochement
from . import test_appareil
from . import test_qualification
from . import test_note
from . import test_liens_crm
from . import test_audit
from . import test_indicateurs
from . import test_couverture
from . import test_relance_affaires
from . import test_retention
from . import test_recherche
from . import test_enrichissement
from . import test_notes_compte
from . import test_perimetre_recherche
from . import test_activites
from . import test_indicatif_pays
